name: my_login_app
description: A new Flutter project.
environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0